### ISSUE TITLE
OLED version of Ubuntu Focal for NanoPi NEO2

### ISSUE THREAD

**Issue by VVakko** [friendlyarm/NanoHatOLED#12]
Please publish file nanopi-neo2_sd_ubuntu-olde-focal_4.14_arm64_20210616.img.gz anywhere except baidu.

**Comment by friendlyarm** [comment]
Thank you for your feedback, it has been fixed.


Please visit this link:
https://drive.google.com/open?id=1QLdZM_duUE0QzdUi5_nQEge_KdfVegeT

Goto:
NanoPi-NEO2 / official-ROMs / accessory-ROMs
