### ISSUE TITLE
可以增加天气功能吗

### ISSUE THREAD

**Issue by yanaex** [friendlyarm/NanoHatOLED#6]
还有中文版本。。

**Comment by vinewx** [comment]
已加入年进度条和天气功能
- OpenWRT 插件: [NanoHatOLED](https://github.com/vinewx/NanoHatOLED)
- 预编译版固件: [NanoWrt](https://github.com/vinewx/NanoWrt)
<img src="https://github.com/vinewx/NanoHatOLED/raw/weather/assets/k1.jpg" width="200" /> <img src="https://github.com/vinewx/NanoHatOLED/raw/weather/assets/k2_1.jpg" width="200" /> <img src="https://github.com/vinewx/NanoHatOLED/raw/weather/assets/k2_2.jpg" width="200" /> <img src="https://github.com/vinewx/NanoHatOLED/raw/weather/assets/k3.jpg" width="200" />

**Comment by yanaex** [comment]
nice！
